services:
  web:
    build:
      context: .
    command: ./docker-entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - tlsn_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  tlsn_db:
