default: &default
  adapter: postgresql
  encoding: unicode

  host: localhost
  username: postgres
  password: postgres

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: the_last_social_network_development

test:
  <<: *default
  database: the_last_social_network_test

production:
  <<: *default
  database: the_last_social_network_production
  username: the_last_social_network
  password: <%= ENV["THE_LAST_SOCIAL_NETWORK_DATABASE_PASSWORD"] %>
